### ISSUE TITLE
Benchmark Code

### ISSUE THREAD

**Issue by kpango** [yahoojapan/ngtd#25]

**Comment by cloverrose** [comment]
I'd like to try this job.

I think it is easy to use ngtd insert api for setup index, but ngtd  can't start up without NGT index.
So, at first we should fix this problem. I'll make this issue with detail info.

**Comment by cloverrose** [comment]
Oh, I'm sorry this problem does not happen now (and may did not happen)
I can create index from scratch by only use ngtd HTTP API.

**Comment by cloverrose** [comment]
On the first phase I try to add search (or searchbyid) benchmark code.

For it I think it is useful to add dummy db which does not use any real db to ignore db specific performance differences or change.
Do you have any concern about it?

**Comment by kpango** [comment]
As a precaution, I think that it is necessary to make the vector data as unbalanced as possible so as not to bias the vector data as a benchmark.

**Comment by kpango** [comment]
I mean you should write BenchmarkXXX function code in xxx_benchmark_test.go.
After that you should write e2e test code using JMeter or Vegeta or ApacheBench.
I strongly recommend create e2e test package inside the ngtd using using vegeta sdk.

**Comment by cloverrose** [comment]
Oh I see. I'm a Go newbie, so it may takes time.

**Comment by kpango** [comment]
It's okay, I'm proficient in Golang. I can review your code.

**Comment by cloverrose** [comment]
Thank you!! 😄

**Comment by kpango** [comment]
Although this is a complete digression, I'm already headed to the next version of ngtd (clusterize & native core api).If you do not have time right now, you can cooperate after publishing the next version.
