### ISSUE TITLE
pprof option makes some error

### ISSUE THREAD

**Issue by cloverrose** [yahoojapan/ngtd#27]
After merged #23 , I tried to run it.
But I can not start ngtd when pass `--pprof` option.

I fixed comma-less Name problem
```go
cli.BoolFlag{
	Name:  "pprof, pp", // HERE
	Usage: "enable pprof server",
},
```
but ngtd does not start.

This problem happens ONLY when with pprof option, so it is not critical now.

**Comment by kpango** [comment]
Can you check on NGTD:1.1.1

**Comment by cloverrose** [comment]
Sorry for my misleading message,
I used ver 1.1.1 and fixed comma-less Name problem.

**Comment by kpango** [comment]
Can you show me the start up command?

**Comment by cloverrose** [comment]
on commit 570b4bd it works without pprof option

```
sudo rm -rf /var/debug-ngtd && sudo mkdir -p /var/debug-ngtd

sudo docker run --name ngtd-container -p 80:8200 -v /var/debug-ngtd:/var/data -itd ngtd:latest \
  http -i /var/data/index -d 8 -t bolt -p /var/data/db 

curl http://localhost/dimension
{"dimension":8}
```

but with pprof option it cause error (comma less bug).
After fixed it, curl does not finish with pprof option

```
sudo docker stop ngtd-container && sudo docker rm ngtd-container
sudo rm -rf /var/debug-ngtd && sudo mkdir -p /var/debug-ngtd

sudo docker run --name ngtd-container -p 80:8200 -v /var/debug-ngtd:/var/data -itd ngtd:latest \
  http -i /var/data/index -d 8 -t bolt -p /var/data/db --pprof

curl http://localhost/dimension
CTR-C
```
